[[mgr.prepend_keymap]]
on = "<C-p>"
run = "shell -- qlmanage -p %s"
desc = "Open Quick Look (MacOS)"

# ya pkg add ciarandg/cd-git-root
[[manager.prepend_keymap]]
on   = ["g", "r"]
run  = "plugin cd-git-root"
desc = "Go to Git repo root"

# ya pkg add yazi-rs/plugins:vcs-files
[[mgr.prepend_keymap]]
on   = [ "g", "c" ]
run  = "plugin vcs-files"
desc = "Show Git file changes"
