start-at-login = true

# Temporarily disabled to see if this makes JankyBorders crash.
# Try `brew services start borders` instead.
# after-startup-command = [
#   'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 hidpi=on 2>/dev/null 1>&2 &'
# ]

exec-on-workspace-change = [
    '/bin/bash', '-c',
    '~/.config/aerospace/pip-move',
]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = 'accordion'
default-root-container-orientation = 'horizontal'

automatically-unhide-macos-hidden-apps = true

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center', 'exec-and-forget ~/.config/share-focus/sync']

accordion-padding = 20

[gaps]
    inner.horizontal = 0
    inner.vertical =   0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0
    outer.left =       0

# General binding rules:
# - Meh key to focus (alt-ctrl-shift)
# - Hyper key to move (alt-ctrl-shift-cmd)

# Avoid conflicts if using just alt: e o a s l z x c n   f   h j k l

[mode.main.binding]

    # Manually exec sync for commands that don't change window focus

    # Layout
    alt-ctrl-shift-e = ['layout accordion horizontal vertical', 'exec-and-forget ~/.config/share-focus/sync']
    alt-ctrl-shift-r = ['layout tiles horizontal vertical', 'exec-and-forget ~/.config/share-focus/sync']
    alt-ctrl-shift-f = ['fullscreen', 'exec-and-forget ~/.config/share-focus/sync']
    alt-ctrl-shift-cmd-f = ['layout floating tiling ', 'exec-and-forget ~/.config/share-focus/sync']

    alt-ctrl-shift-tab = 'exec-and-forget aerospace focus-back-and-forth || aerospace workspace-back-and-forth'
    alt-ctrl-shift-cmd-tab = ['move-workspace-to-monitor --wrap-around next', 'exec-and-forget ~/.config/share-focus/sync']

    alt-ctrl-shift-cmd-semicolon = 'mode service'

    cmd-h = [] # Disable "hide application"
    cmd-m = [] # Disable "minimize application"
    cmd-alt-ctrl-shift-h = [] # Disable "hide others"

    # Resizing
    alt-ctrl-shift-minus = ['resize smart -100', 'exec-and-forget ~/.config/share-focus/sync']
    alt-ctrl-shift-equal = ['resize smart +100', 'exec-and-forget ~/.config/share-focus/sync']

    # Focus
    alt-ctrl-shift-h = 'focus left'
    alt-ctrl-shift-j = 'focus down'
    alt-ctrl-shift-k = 'focus up'
    alt-ctrl-shift-l = 'focus right'

    # Focus specific windows
    alt-ctrl-shift-enter = 'exec-and-forget ~/.config/aerospace/focus-app "Android Studio"'
    alt-ctrl-shift-space = 'exec-and-forget ~/.config/aerospace/focus-app "Ghostty"'

    # Move window direction
    alt-ctrl-shift-cmd-h = ['move left', 'exec-and-forget ~/.config/share-focus/sync']
    alt-ctrl-shift-cmd-j = ['move down', 'exec-and-forget ~/.config/share-focus/sync']
    alt-ctrl-shift-cmd-k = ['move up', 'exec-and-forget ~/.config/share-focus/sync']
    alt-ctrl-shift-cmd-l = ['move right', 'exec-and-forget ~/.config/share-focus/sync']

    # Workspace
    alt-ctrl-shift-y = ['workspace Y', 'focus dfs-next --boundaries-action wrap-around-the-workspace']
    alt-ctrl-shift-u = ['workspace U', 'focus dfs-next --boundaries-action wrap-around-the-workspace']
    alt-ctrl-shift-i = ['workspace I', 'focus dfs-next --boundaries-action wrap-around-the-workspace']
    alt-ctrl-shift-o = ['workspace O', 'focus dfs-next --boundaries-action wrap-around-the-workspace']
    alt-ctrl-shift-p = ['workspace P', 'focus dfs-next --boundaries-action wrap-around-the-workspace']

    # Move to workspace
    alt-ctrl-shift-cmd-y = ['move-node-to-workspace --focus-follows-window Y', 'exec-and-forget ~/.config/share-focus/sync']
    alt-ctrl-shift-cmd-u = ['move-node-to-workspace --focus-follows-window U', 'exec-and-forget ~/.config/share-focus/sync']
    alt-ctrl-shift-cmd-i = ['move-node-to-workspace --focus-follows-window I', 'exec-and-forget ~/.config/share-focus/sync']
    alt-ctrl-shift-cmd-o = ['move-node-to-workspace --focus-follows-window O', 'exec-and-forget ~/.config/share-focus/sync']
    alt-ctrl-shift-cmd-p = ['move-node-to-workspace --focus-follows-window P', 'exec-and-forget ~/.config/share-focus/sync']

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout

    alt-ctrl-shift-cmd-h = ['join-with left', 'exec-and-forget ~/.config/share-focus/sync', 'mode main']
    alt-ctrl-shift-cmd-j = ['join-with down', 'exec-and-forget ~/.config/share-focus/sync', 'mode main']
    alt-ctrl-shift-cmd-k = ['join-with up', 'exec-and-forget ~/.config/share-focus/sync', 'mode main']
    alt-ctrl-shift-cmd-l = ['join-with right', 'exec-and-forget ~/.config/share-focus/sync', 'mode main']

[workspace-to-monitor-force-assignment]
    Y = ['built-in', 'DELL']
    U = ['DELL', 'built-in']
    I = ['DELL', 'built-in']
    O = ['DELL', 'built-in']
    P = ['built-in', 'DELL']

[[on-window-detected]]
    if.app-id = 'com.mitchellh.ghostty'
    run = 'move-node-to-workspace U'

[[on-window-detected]]
    if.app-id = 'com.google.android.studio'
    run = 'move-node-to-workspace I'

[[on-window-detected]]
    if.app-id = 'com.google.android.studio-EAP'
    run = 'move-node-to-workspace I'

[[on-window-detected]]
    if.app-id = 'com.jetbrains.intellij.ce'
    run = 'move-node-to-workspace I'

[[on-window-detected]]
    if.app-id = 'org.mozilla.firefox'
    run = 'move-node-to-workspace O'

[[on-window-detected]]
    if.app-id = 'com.google.Chrome'
    run = 'move-node-to-workspace O'

[[on-window-detected]]
    if.app-id = 'com.microsoft.edgemac'
    run = 'move-node-to-workspace O'

[[on-window-detected]]
    if.app-id = 'com.tinyspeck.slackmacgap'
    run = 'move-node-to-workspace P'

[[on-window-detected]]
    if.app-id = 'com.apple.Notes'
    run = 'move-node-to-workspace P'

[[on-window-detected]]
    if.app-id = 'md.obsidian'
    run = 'move-node-to-workspace P'

[[on-window-detected]]
    if.app-id = 'com.spotify.client'
    run = 'move-node-to-workspace P'

[[on-window-detected]]
    if.window-title-regex-substring = 'Picture-in-Picture'
    run = 'layout floating'

[[on-window-detected]]
    check-further-callbacks = true
    run = 'layout floating'

